name: flutter_marquee
description: A new Flutter package.
version: 2.0.2
repository: https://github.com/openusen/flutter_marquee

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter